server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: graphrag-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# 项目
graphrag:
  root: D:\.py\PythonProject\graphrag

neo4j:
  root: D:\Neo4j\neo4j-community-5.22.0
  uri: bolt://localhost:7687
  username: neo4j
  password: neo4j

file:
  upload:
    path: ${graphrag.root}\input
    max-size: 10485760  # 10MB
python-venv:
  #
  path: D:\VirtualVenv\graphrag
  activate: ${python-venv.path}\Scripts\activate.bat
  interpreter: ${python-venv.path}\Scripts\python

# swagger配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
