server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: graphrag-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

graphrag:
  root: D:\.py\PythonProject\graphrag

neo4j:
  root: D:\Neo4j\neo4j-community-5.22.0

file:
  upload:
    path: ${user.dir}/uploads
    max-size: 10485760  # 10MB
